---
endpoints:
  - &common-mirror
    name: mirror-ghcr
    group: sakamoto
    url: "tcp://sakamoto.lan:5001"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: custom
  - <<: *common-mirror
    name: mirror-quay
    url: "tcp://sakamoto.lan:5002"
  - <<: *common-mirror
    name: mirror-mirror-gcr
    url: "tcp://sakamoto.lan:5003"
  - <<: *common-mirror
    name: mirror-k8s
    url: "tcp://sakamoto.lan:5005"
  - <<: *common-mirror
    name: sakamoto-caddy
    url: "tcp://sakamoto.lan:443"
  - <<: *common-mirror
    name: minio-local
    url: "tcp://sakamoto.lan:9000"
  - name: minio-domain
    group: sakamoto
    url: https://minio.${MAIN_DOMAIN}/minio/health/live
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: nvidia-dls
    group: sakamoto
    url: https://sakamoto.lan:5100/-/health
    method: HEAD
    interval: 1m
    client:
      insecure: true
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 405" # HEAD 请求
    alerts:
      - type: custom
  - name: kopia
    group: sakamoto
    url: http://sakamoto.lan:51515/
    method: HEAD
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: kopia-local
    group: sakamoto
    url: http://sakamoto.lan:51516/
    method: HEAD
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - name: dockerproxy
    group: sakamoto
    url: http://sakamoto.lan:2575/_ping
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == OK"
    alerts:
      - type: custom
