---
endpoints:
  - &common
    name: subconverter
    group: vps
    url: https://sub.${MAIN_DOMAIN}/version
    interval: 2m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
  - <<: *common
    name: derp
    url: https://derp.${MAIN_DOMAIN}
  - <<: *common
    name: vps-caddy
    url: "tcp://ts-node-vps.network.svc:443"
    interval: 2m
    conditions:
      - "[CONNECTED] == true"
    ui: {}
  - <<: *common
    name: dockerproxy
    url: http://ts-node-vps.network.svc:2575/_ping
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == OK"
  - name: mosdns
    group: vps
    url: ts-node-vps.network.svc:5054
    interval: 2m
    dns:
      query-name: openai.com
      query-type: A
    ui:
      hide-hostname: true
      hide-url: true
      hide-conditions: true
    conditions:
      - "[CONNECTED] == true"
      - "[DNS_RCODE] == NOERROR"
      - "[BODY] == pat(*.*.*.*)"
    alerts:
      - type: custom
  - <<: *common
    name: openlist
    url: http://ts-node-vps.network.svc:5244/api/public/settings
    method: HEAD
  - <<: *common
    name: kopia
    url: http://ts-node-vps.network.svc:51515/
    method: HEAD
  - <<: *common
    name: vps-node-exporter
    url: "tcp://ts-node-vps.network.svc:9100"
    conditions:
      - "[CONNECTED] == true"
  # - <<: *common
  #   name: vless-reality
  #   url: "tcp://ts-node-vps.network.svc:5443"
  #   conditions:
  #     - "[CONNECTED] == true"
  - <<: *common
    name: hysteria2
    url: http://ts-node-vps.network.svc:2575/containers/hysteria2/json
    conditions:
      - "[STATUS] == 200"
      - "[BODY].State.Running == true"
      - "[BODY].State.Restarting == false"
      - "[BODY].State.Dead == false"
  - <<: *common
    name: dhp
    url: https://dhp.${MAIN_DOMAIN}/v2/
    method: HEAD
