---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-init-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: litellm-init-db-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: "litellm"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "litellm"
        INIT_POSTGRES_PASS: "{{ .LITELLM_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: litellm

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: litellm-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://litellm:{{ .LITELLM_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/litellm"
        REDIS_HOST: "dragonfly.database.svc.cluster.local"
        OR_SITE_URL: "https://llm.${MAIN_DOMAIN}"
        OR_APP_NAME: "LiteLLM"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        DEEPSEEK_API_KEY_1: "{{ .DEEPSEEK_API_KEY_1 }}"
        OPENROUTER_API_KEY_1: "{{ .OPENROUTER_API_KEY_1 }}"
        OPENROUTER_API_KEY_2: "{{ .OPENROUTER_API_KEY_2 }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: cli-proxy-api
