---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret ss-rust
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: ss-rust-secret
    template:
      data:
        SS_PASSWORD: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: ss-rust
