keys:
  - &admin_mio age1kmr8epyg0et773rg4x2hquu3ylua72xyzcu7lw2hf9g5l7nrzuyslexq35
  - &home-ops age12uqzp3ezd2q2z5wkrd8mjprneypgskm2ve4takjp700hyu4l49nsa5jxkw
creation_rules:
  - path_regex: (k8s)/.+\.sops\.(ya?ml)
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
        - *admin_mio
        - *home-ops
stores:
  yaml:
    indent: 2
