---
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kopiur/main/deploy/crds/clusterrepositories.yaml
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: sakamoto
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
      bucket: kopiur
      endpoint: sakamoto.lan:9000
      tls:
        disableTls: true
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  maintenance:
    schedule:
      quick:
        cron: 0 * * * *
        jitter: 10m
      full:
        cron: 0 3 * * *
        jitter: 1h
  moverDefaults:
    cache:
      contentCacheSizeMb: 512
      metadataCacheSizeMb: 1024
  parameters:
    epoch:
      minDuration: 1h
  scheduleDefaults:
    timezone: ${TIMEZONE}
