---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-init-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: memos-init-db-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: memos
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: memos
        INIT_POSTGRES_PASS: "{{ .MEMOS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: memos

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: memos-secret
    template:
      data:
        # memos
        MEMOS_DSN: postgresql://memos:{{ .MEMOS_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/memos
  dataFrom:
    - extract:
        key: memos

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-idp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: memos-idp-secret
    template:
      data:
        memos-idp-authelia.json: |
          {
            "uid": "00000002",
            "name": "Authelia",
            "type": "OAUTH2",
            "identifierFilter": "",
            "config": {
              "oauth2Config": {
                "clientId": "memos",
                "clientSecret": "{{ .MEMOS_OAUTH_CLIENT_SECRET }}",
                "authUrl": "https://auth.${MAIN_DOMAIN}/api/oidc/authorization",
                "tokenUrl": "https://auth.${MAIN_DOMAIN}/api/oidc/token",
                "userInfoUrl": "https://auth.${MAIN_DOMAIN}/api/oidc/userinfo",
                "scopes": ["openid", "profile", "email"],
                "fieldMapping": {
                  "identifier": "preferred_username",
                  "displayName": "given_name",
                  "email": "email",
                  "avatarUrl": "picture"
                }
              }
            }
          }
  dataFrom:
    - extract:
        key: memos
