system_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - zsh

# 换源设置
change_mirror: false

# 安装 Docker
enable_install_docker: true

# 安装 Tailscale
enable_install_tailscale: true

# 安装 Oh My Zsh
enable_install_ohmyzsh: true

# SSH
ssh_port: 60223
ssh_disable_password_login: true

# UFW
ufw_allowed_rules:
  - 22/tcp
  - 443/tcp
  - 443/udp
  - 8666/tcp # derp
  - 3478/udp # derp
  - "5201" # iperf3
  - "10357" # hy2
  - "10358" # hy2 + no-obfs
  - "5444" # anytls
  - 60223/tcp # ssh

# 服务商路径 MTU 低于 1500；实测 IPv6 DF@1400 失败、@1350 成功
interface_mtu:
  enabled: true
  interface: eth0
  mtu: 1400
