---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icache-cache
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/filesystem-trim: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-cache
  resources:
    requests:
      storage: 20Gi
