---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cpa-usage-keeper
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: cpa-usage-keeper-secret
    template:
      engineVersion: v2
      data:
        CPA_MANAGEMENT_KEY: "{{ .MANAGEMENT_PASSWORD }}"
        LOGIN_PASSWORD: "{{ .MANAGEMENT_PASSWORD }}"
  dataFrom:
    - extract:
        key: cli-proxy-api
