---
# - import_playbook: ./send-files.yml

- name: 安装并配置k3s
  hosts: all
  become: true
  gather_facts: true
  handlers:
    - name: restart k3s
      ansible.builtin.service:
        name: k3s
        state: restarted
      when: k3s_control_node | default(false) | bool

  tasks:
    - name: K3s audit policy
      ansible.builtin.include_tasks: tasks/k3s-audit.yaml
      when: k3s_control_node | default(false) | bool

    - name: Install Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed

    - name: Kubeconfig
      ansible.builtin.include_tasks: tasks/kubeconfig.yaml

    # - name: send files
    #   ansible.builtin.include_tasks: send-files.yaml
