# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cli-proxy-api
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store
  target:
    name: cli-proxy-api-secret
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: cli-proxy-api-config-tpl
            items:
              - key: config.yaml
                templateAs: Values

  dataFrom:
    - extract:
        key: cli-proxy-api
