---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cli-proxy-api
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      cli-proxy-api:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: eceasy/cli-proxy-api
              tag: v6.9.38@sha256:5d71649bd5ba69e35bc069e878326e686bdd67ce0d57c693796dfa6bf9b8094e
            env:
              TZ: ${TIMEZONE}
              MANAGEMENT_STATIC_PATH: &management /CLIProxyAPI/management
            # 注释为了不想在日志中出现大量这个接口
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /healthz
            #         port: &port 8317
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 10
            #   readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.69.60
        externalTrafficPolicy: Local
        ports:
          api:
            port: &port 8317
          gemini:
            port: 8085
          codex:
            port: 1455
          # anthropic:
            # port: 54545
          ## ./CLIProxyAPI --antigravity-login --no-browser
          antigravity:
            port: 51121
          # iflow:
          #   port: 11451
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: internal
          gethomepage.dev/name: *app
          gethomepage.dev/app: *app
          gethomepage.dev/icon: kubernetes-dashboard.svg
        hostnames: ["{{ .Release.Name }}.${MAIN_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      app-external:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: external
          gethomepage.dev/name: *app
          gethomepage.dev/icon: kubernetes-dashboard.svg
          gethomepage.dev/app: *app
          gatus.home-operations.com/endpoint: |-
            conditions:
              - "[STATUS] == 404"
        hostnames: ["cpa.${MAIN_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https-cpa
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /v1
            backendRefs:
              - identifier: app
                port: *port
    persistence:
      auths:
        existingClaim: cli-proxy-api
        advancedMounts:
          cli-proxy-api:
            app:
              - path: /root/.cli-proxy-api
                subPath: auths
              - path: /.cli-proxy-api
                subPath: for-run
      config-file:
        type: secret
        name: cli-proxy-api-secret
        globalMounts:
          - path: /CLIProxyAPI/config.yaml
            subPath: config.yaml
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /CLIProxyAPI/logs
            subPath: logs
          - path: *management
            subPath: management
