---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

vps-docker:
  conn:
    host: ts-node-vps.network.svc
    port: 2575
    connectionTimeout: 5000
    timeout: 5000

sakamoto-docker:
  conn:
    host: sakamoto.lan
    port: 2575
    connectionTimeout: 5000
    timeout: 5000
