apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:z3E7EWNS3FJxMazOuVLXT0i3fmsHR2ITxMdbA3H6R17kims1x8vZ4/vK2YnOBad4t7Qe+9FIekG44O1UrRjOXDNu3mL/6hz8OZA=,iv:mh7S5KB5zxG1X16rXp8FJqiPm5Tw2YVEL1ZUa9wg+Z0=,tag:ogDhQ85duCqQ9d39Popwkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMGZmN1RxOVVOd2M1Q0Fu
        bU03SjhUVXkzYTFuK2luTnN5YXA3bzVXSkhNCm1OdGtPWCtKTVhZNDRMQmphLzRH
        dktpVHhyYjY1TnE1VGppUFl6allSOVUKLS0tIEhaL0FpQVJsaXpRRytvQk45RUVo
        QUpmeWx3RWw1T1F5N2FaVGI4VmYvMWsKxk8HoueRAS1jLW2M5q1kPbCyefb3hAAz
        uAyy9WvCQGrhG1YIfWC7Jw+51YriR35bkz4gnnXYrnbHAlcSsZp+UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ajrupd6znrpz2jxs9dnmdjhu2j2lf27q769dnlnyhfk9460a446q9ez9wl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ajVVRDFpNzU1Wm5oTEow
        NytXM29zSnFRWXhOcUhmUjQvcFNSa2V1ckY0CmhnWnpYTTBPaFRLQ0tMMG5vS0E1
        OUV1M2Z1S1Bad3BWbnRObEg4OWFTNUkKLS0tIFRyNVRXaHBIT2VmRjBzWjAzTnlT
        MmRId0c0RGoxMnpNNnhrT3VycEI5eXMKAphxa1vspkQZyBWbEJzr8YYgDiyI2lyF
        F0r77uS3NmYubbiGrrM+9IRUPWS2WIwRri/CqJlK1mwN3qq6J4G4iQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12uqzp3ezd2q2z5wkrd8mjprneypgskm2ve4takjp700hyu4l49nsa5jxkw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-06-20T10:53:07Z"
  mac: ENC[AES256_GCM,data:0QlBbt3q3SeLorla/KGBi4nG6YxfDtuWOqsX8W/2plldwW0s0BqXPHfodVbhLnJSbF5lLQQpJtUTtxFogymKmrBZnUBGex4QYtf9OlJ5RL2JI/I5m/kkjssD0yb8MfHMqpF5pEPvUfaA1nCW2sU5ygsQBoC1Crjn7Wu0afZxeUY=,iv:wvJLgLwmio4gMap6uwBnLvPpNO1sLw1CrYr0i4PbYrU=,tag:LK/6bv5dP4A+rroeqD1r8Q==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
