apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:PK8UOdQv4jFCCOR/w4UheKAVEBTK0NE+6bsg7+H6O3FdXlG1Tk8f9ds8HDelSz9xiC8178vf5clJaMUFULRfsidoZFO68l6mlA0=,iv:AGpBHzeElwJJRsvo2uBkDzf9QdojQiEFI2Q6tY/U+ic=,tag:0+wrpfd8OLPEkg8WVsk2JQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc0RaVkYwTVZsYmdrVWVN
        Yy9VVzVUWTJMK1NQazQwSGg2WGNrQ0tzZ0UwCkNuNExNNFRZWk9UQnB4N3FVdExZ
        RU02Q0g0MlBmSkR6Ui9FN1Yrd21tWmsKLS0tIDVYZjZ5UlM5b2hHSUNPWmY4U0xK
        Y21wQ0lHWDNvalpFVG05MzBtNnJvcWsKTMbDY0+63DDbaSV03D055BRvYinXU5c3
        pq+mbEx5MHYww6f9ys5azsF+WRKy+rgBxh2SyOpnqSFxMSU4oc6cCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kmr8epyg0et773rg4x2hquu3ylua72xyzcu7lw2hf9g5l7nrzuyslexq35
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUc5ZWhweVFGTVJ5NE80
        cXdTTkpTSTQyLzFhdnV4cmRtVXhoYm9WNVI0CnkxVDc2dFNkR1piV0U2aTNSeFVG
        eE1VYkNFU0J5bFQrbm4rZ0ZMaitudTAKLS0tIFpTMjQ2eGl1YURQVzBjUDZPRkVT
        cEQ4L290TU8vQWZOeHhqa1lrUWpTQjAKxGm614riHFgMyF6AwrEJR8qv1MLHJQ/d
        plJmj6n462X+FYkks0T+uRMpF2rvuoTpkDy8bR9mOc/w/YLkqZW7XA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gjms24erernqu5cqv8fz56ck6lye0s3c0jtf3yy4nszj5fl5sq9q0s93mv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T22:46:12Z"
  mac: ENC[AES256_GCM,data:v6/dQ2362EgRHXpxeuwIUK4aDFIahRcxxdKKPU6/bg1tQkuufK+XvEw29/b1qNSh4Lje7AriIya1bS5gQW0icX6hB/IzRKEljQch/YkCkAGORCsNziN+o0xlbfyPvqo6wB9mk3ojoTGDqqFOATqCbEkTVV9G8nQt+9EseAEvHU0=,iv:xDrBhrTHfi/UmArvq7inSc325tx78nElP8KRJeyv560=,tag:G7IW4RkHyI49x4LlGxgoeQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
